export const FISH_SPECIES = [
  "Largemouth Bass",
  "Smallmouth Bass",
  "Northern Pike",
  "Walleye",
  "Muskellunge",
  "Panfish",
  "Longnose Gar",
  "Common Carp",
  "Channel Catfish",
  "Lake Trout",
  "Brook Trout",
  "Rainbow Trout",
  "Brown Trout",
  "Chinook Salmon",
  "Coho Salmon",
  "Atlantic Salmon",
];

export const SPECIES_PROFILES = {
  "Largemouth Bass": {
    rarityModifier: 10,
    category: "Warmwater Sportfish",
    difficultyBias: "Beginner to Intermediate",
    preferredConditions: "Weedy bays, docks, fallen timber, and warm shallow water from late spring through summer.",
    recommendedMethods: "Cast spinnerbaits, soft plastics, topwater lures, or live bait around cover.",
    note: "One of Ontario's most accessible sportfish and a strong choice for newer anglers.",
  },
  "Smallmouth Bass": {
    rarityModifier: 8,
    category: "Warmwater Sportfish",
    difficultyBias: "Beginner to Intermediate",
    preferredConditions: "Rocky shorelines, points, shoals, and clear lakes or rivers with moderate current.",
    recommendedMethods: "Use tubes, drop-shot rigs, crankbaits, jerkbaits, or live minnows near rock and depth changes.",
    note: "Common across much of Ontario and often easier to pattern around rock structure.",
  },
  "Northern Pike": {
    rarityModifier: 2,
    category: "Predator",
    difficultyBias: "Intermediate",
    preferredConditions: "Weed edges, shallow bays, river mouths, and cooler water near ambush cover.",
    recommendedMethods: "Cast spoons, spinners, jerkbaits, swimbaits, or large minnows with a wire leader.",
    note: "A widespread predator that can be aggressive, but larger fish take more patience and careful handling.",
  },
  Walleye: {
    rarityModifier: 0,
    category: "Coolwater Sportfish",
    difficultyBias: "Intermediate",
    preferredConditions: "Low light, stained water, wind-blown points, rocky shoals, current seams, and deeper edges.",
    recommendedMethods: "Try jig-and-minnow rigs, bottom bouncers, trolling crankbaits, or slow spinner rigs.",
    note: "A classic Ontario target that is common in many waters but often rewards timing and depth control.",
  },
  Muskellunge: {
    rarityModifier: -35,
    category: "Trophy Predator",
    difficultyBias: "Advanced",
    preferredConditions: "Large weed flats, rocky points, deep weed edges, and major structure on big lakes and rivers.",
    recommendedMethods: "Throw large bucktails, jerkbaits, glide baits, or troll oversized crankbaits with heavy gear.",
    note: "Ontario's fish of ten thousand casts; rare, specialized, and best treated as a dedicated trophy pursuit.",
  },
  Panfish: {
    rarityModifier: 18,
    category: "Panfish",
    difficultyBias: "Beginner",
    preferredConditions: "Shallow weeds, docks, sheltered bays, and warm nearshore areas, especially in spring and summer.",
    recommendedMethods: "Use small hooks, worms, tiny jigs, bobbers, or micro spinners close to cover.",
    note: "Common, approachable, and ideal for families or first-time anglers across many Ontario waters.",
  },
  "Longnose Gar": {
    rarityModifier: -22,
    category: "Specialty Fish",
    difficultyBias: "Advanced",
    preferredConditions: "Warm shallow bays, slow rivers, backwaters, and calm surface water in summer.",
    recommendedMethods: "Sight-fish with rope lures, small baitfish presentations, or patient surface approaches.",
    note: "A rare and specialized target in Ontario that requires careful timing, location, and handling.",
  },
  "Common Carp": {
    rarityModifier: 6,
    category: "Coarse Fish",
    difficultyBias: "Beginner to Intermediate",
    preferredConditions: "Warm bays, harbours, slow rivers, muddy flats, and areas with soft bottom.",
    recommendedMethods: "Fish corn, dough bait, boilies, or hair rigs on bottom with light drag and patience.",
    note: "Often abundant in southern Ontario and surprisingly strong once hooked.",
  },
  "Channel Catfish": {
    rarityModifier: 1,
    category: "River Fish",
    difficultyBias: "Intermediate",
    preferredConditions: "Large rivers, deep holes, current breaks, and warm evening or night conditions.",
    recommendedMethods: "Use cut bait, worms, shrimp, or stink bait on bottom rigs near current and depth.",
    note: "A dependable warmwater option in suitable Ontario rivers and reservoirs.",
  },
  "Lake Trout": {
    rarityModifier: -12,
    category: "Coldwater Trout",
    difficultyBias: "Intermediate to Advanced",
    preferredConditions: "Deep, cold, clear lakes, especially around drop-offs, basins, and summer thermoclines.",
    recommendedMethods: "Troll spoons, downriggers, lead core, jig heavy tubes, or ice fish deep structure.",
    note: "Seasonal and depth-focused, with strong habitat needs and more specialized equipment.",
  },
  "Brook Trout": {
    rarityModifier: -10,
    category: "Coldwater Trout",
    difficultyBias: "Intermediate",
    preferredConditions: "Cold streams, spring-fed ponds, small lakes, and shaded water with good oxygen.",
    recommendedMethods: "Use small spinners, flies, worms, or tiny spoons with stealthy presentations.",
    note: "A prized Ontario trout that can be accessible in the right water but is sensitive to conditions.",
  },
  "Rainbow Trout": {
    rarityModifier: -8,
    category: "Coldwater Trout",
    difficultyBias: "Intermediate",
    preferredConditions: "Cold tributaries, river mouths, stocked lakes, and seasonal spring or fall runs.",
    recommendedMethods: "Drift roe, beads, flies, spinners, spoons, or float rigs depending on the water.",
    note: "Often seasonal and location-specific, especially around Great Lakes tributaries.",
  },
  "Brown Trout": {
    rarityModifier: -9,
    category: "Coldwater Trout",
    difficultyBias: "Intermediate to Advanced",
    preferredConditions: "Cold streams, harbour mouths, rocky shorelines, and low-light feeding windows.",
    recommendedMethods: "Cast spinners, spoons, stickbaits, streamers, or drift natural baits carefully.",
    note: "Can be wary and seasonal, making stealth and timing more important than raw casting volume.",
  },
  "Chinook Salmon": {
    rarityModifier: -14,
    category: "Salmon",
    difficultyBias: "Intermediate to Advanced",
    preferredConditions: "Great Lakes open water in summer and tributary mouths or rivers during fall runs.",
    recommendedMethods: "Troll spoons, flashers, flies, plugs, or fish roe and skein during river staging periods.",
    note: "A seasonal powerhouse that depends heavily on migration timing and Great Lakes access.",
  },
  "Coho Salmon": {
    rarityModifier: -16,
    category: "Salmon",
    difficultyBias: "Intermediate to Advanced",
    preferredConditions: "Great Lakes shorelines, river mouths, and tributaries during cooler seasonal windows.",
    recommendedMethods: "Cast spoons, spinners, plugs, or troll small flashers and flies near staging fish.",
    note: "Less predictable than Chinook in many Ontario spots, but excellent when seasonal runs line up.",
  },
  "Atlantic Salmon": {
    rarityModifier: -20,
    category: "Salmon",
    difficultyBias: "Advanced",
    preferredConditions: "Select cold tributaries, restoration waters, and seasonal migration corridors.",
    recommendedMethods: "Use flies, small spoons, spinners, or drift presentations where regulations allow.",
    note: "A rare and highly regulated Ontario target, usually tied to specific waters and restoration programs.",
  },
};

export const PRESSURE_MODIFIERS = {
  low: 8,
  medium: 0,
  high: -8,
  veryHigh: -15,
};

export const ACCESSIBILITY_MODIFIERS = {
  low: -10,
  medium: 0,
  high: 8,
  veryHigh: 12,
};

export const WATERS = [
  {
    id: "lake-ontario-toronto-waterfront",
    name: "Lake Ontario - Toronto Waterfront",
    type: "Great Lake",
    region: "Toronto",
    lat: 43.627,
    lon: -79.371,
    species: ["Common Carp", "Panfish", "Smallmouth Bass", "Northern Pike", "Chinook Salmon", "Coho Salmon", "Rainbow Trout", "Brown Trout"],
    pressureLevel: "veryHigh",
    accessibility: "veryHigh",
    tags: ["great-lake", "urban-shore", "harbour"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "toronto-islands-lagoon",
    name: "Toronto Islands Lagoons",
    type: "Harbour Lagoon",
    region: "Toronto",
    lat: 43.623,
    lon: -79.378,
    species: ["Northern Pike", "Largemouth Bass", "Panfish", "Common Carp", "Longnose Gar"],
    pressureLevel: "veryHigh",
    accessibility: "high",
    tags: ["urban", "shore-access", "warmwater"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "humber-river-lower",
    name: "Humber River - Lower",
    type: "River",
    region: "Toronto",
    lat: 43.637,
    lon: -79.476,
    species: ["Common Carp", "Panfish", "Chinook Salmon", "Coho Salmon", "Rainbow Trout", "Brown Trout"],
    pressureLevel: "veryHigh",
    accessibility: "high",
    tags: ["urban-river", "lake-ontario-tributary", "seasonal-run"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "don-river-lower",
    name: "Don River - Lower",
    type: "River",
    region: "Toronto",
    lat: 43.656,
    lon: -79.354,
    species: ["Common Carp", "Panfish", "Rainbow Trout", "Chinook Salmon"],
    pressureLevel: "veryHigh",
    accessibility: "high",
    tags: ["urban-river", "lake-ontario-tributary", "seasonal-run"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "rouge-river-lower",
    name: "Rouge River - Lower",
    type: "River",
    region: "Scarborough / Pickering",
    lat: 43.801,
    lon: -79.13,
    species: ["Common Carp", "Panfish", "Smallmouth Bass", "Chinook Salmon", "Rainbow Trout", "Brown Trout"],
    pressureLevel: "high",
    accessibility: "high",
    tags: ["urban-edge", "lake-ontario-tributary", "seasonal-run"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "frenchmans-bay",
    name: "Frenchman's Bay",
    type: "Bay",
    region: "Pickering",
    lat: 43.813,
    lon: -79.086,
    species: ["Largemouth Bass", "Northern Pike", "Panfish", "Common Carp", "Channel Catfish"],
    pressureLevel: "high",
    accessibility: "high",
    tags: ["urban-bay", "shore-access", "warmwater"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "credit-river-lower",
    name: "Credit River - Lower",
    type: "River",
    region: "Mississauga",
    lat: 43.552,
    lon: -79.585,
    species: ["Chinook Salmon", "Coho Salmon", "Rainbow Trout", "Brown Trout", "Common Carp"],
    pressureLevel: "veryHigh",
    accessibility: "high",
    tags: ["urban-river", "lake-ontario-tributary", "seasonal-run"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "port-credit-harbour",
    name: "Port Credit Harbour",
    type: "Harbour",
    region: "Mississauga",
    lat: 43.552,
    lon: -79.586,
    species: ["Common Carp", "Panfish", "Smallmouth Bass", "Chinook Salmon", "Coho Salmon", "Rainbow Trout", "Brown Trout"],
    pressureLevel: "veryHigh",
    accessibility: "veryHigh",
    tags: ["harbour", "shore-access", "lake-ontario"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "bronte-creek-lower",
    name: "Bronte Creek - Lower",
    type: "Creek",
    region: "Oakville / Burlington",
    lat: 43.393,
    lon: -79.711,
    species: ["Chinook Salmon", "Rainbow Trout", "Brown Trout", "Common Carp"],
    pressureLevel: "high",
    accessibility: "high",
    tags: ["lake-ontario-tributary", "seasonal-run", "urban-edge"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "sixteen-mile-creek-lower",
    name: "Sixteen Mile Creek - Lower",
    type: "Creek",
    region: "Oakville",
    lat: 43.445,
    lon: -79.668,
    species: ["Chinook Salmon", "Rainbow Trout", "Brown Trout", "Common Carp"],
    pressureLevel: "high",
    accessibility: "high",
    tags: ["lake-ontario-tributary", "seasonal-run", "urban"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "hamilton-harbour",
    name: "Hamilton Harbour",
    type: "Harbour",
    region: "Hamilton / Burlington",
    lat: 43.286,
    lon: -79.851,
    species: ["Common Carp", "Channel Catfish", "Largemouth Bass", "Smallmouth Bass", "Northern Pike", "Panfish"],
    pressureLevel: "veryHigh",
    accessibility: "veryHigh",
    tags: ["urban-harbour", "shore-access", "warmwater"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "bayfront-park-hamilton",
    name: "Bayfront Park",
    type: "Harbour Shoreline",
    region: "Hamilton",
    lat: 43.273,
    lon: -79.872,
    species: ["Common Carp", "Channel Catfish", "Panfish", "Largemouth Bass", "Northern Pike"],
    pressureLevel: "veryHigh",
    accessibility: "veryHigh",
    tags: ["urban", "shore-access", "harbour"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "cooks-bay-lake-simcoe",
    name: "Cook's Bay - Lake Simcoe",
    type: "Bay",
    region: "York / Simcoe",
    lat: 44.211,
    lon: -79.504,
    species: ["Northern Pike", "Largemouth Bass", "Smallmouth Bass", "Panfish", "Walleye"],
    pressureLevel: "veryHigh",
    accessibility: "high",
    tags: ["large-lake", "ice-fishing", "shore-access"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "lake-simcoe-kempenfelt-bay",
    name: "Kempenfelt Bay - Lake Simcoe",
    type: "Bay",
    region: "Barrie / Simcoe",
    lat: 44.385,
    lon: -79.642,
    species: ["Lake Trout", "Smallmouth Bass", "Panfish", "Northern Pike"],
    pressureLevel: "high",
    accessibility: "high",
    tags: ["large-lake", "coldwater", "urban-shore"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "guelph-lake",
    name: "Guelph Lake",
    type: "Reservoir",
    region: "Guelph / Wellington",
    lat: 43.592,
    lon: -80.253,
    species: ["Northern Pike", "Largemouth Bass", "Smallmouth Bass", "Panfish", "Common Carp"],
    pressureLevel: "high",
    accessibility: "high",
    tags: ["reservoir", "shore-access", "urban-adjacent"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "conestogo-lake",
    name: "Conestogo Lake",
    type: "Reservoir",
    region: "Waterloo / Wellington",
    lat: 43.686,
    lon: -80.719,
    species: ["Northern Pike", "Smallmouth Bass", "Panfish", "Common Carp", "Walleye"],
    pressureLevel: "medium",
    accessibility: "medium",
    tags: ["reservoir", "boat-access", "warmwater"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "belwood-lake",
    name: "Belwood Lake",
    type: "Reservoir",
    region: "Centre Wellington",
    lat: 43.751,
    lon: -80.339,
    species: ["Northern Pike", "Smallmouth Bass", "Panfish", "Common Carp", "Walleye"],
    pressureLevel: "high",
    accessibility: "high",
    tags: ["reservoir", "shore-access", "boat-access"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "grand-river-brantford",
    name: "Grand River - Brantford",
    type: "River",
    region: "Brantford",
    lat: 43.139,
    lon: -80.265,
    species: ["Smallmouth Bass", "Walleye", "Channel Catfish", "Common Carp", "Panfish"],
    pressureLevel: "high",
    accessibility: "high",
    tags: ["river", "urban", "warmwater"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "grand-river-dunnville",
    name: "Grand River - Dunnville",
    type: "River",
    region: "Haldimand",
    lat: 42.902,
    lon: -79.617,
    species: ["Channel Catfish", "Walleye", "Smallmouth Bass", "Common Carp", "Panfish", "Longnose Gar"],
    pressureLevel: "high",
    accessibility: "high",
    tags: ["river", "shore-access", "lake-erie-nearshore"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "niagara-river-lower",
    name: "Niagara River - Lower",
    type: "River",
    region: "Niagara",
    lat: 43.161,
    lon: -79.047,
    species: ["Smallmouth Bass", "Walleye", "Lake Trout", "Rainbow Trout", "Brown Trout", "Chinook Salmon", "Coho Salmon"],
    pressureLevel: "high",
    accessibility: "medium",
    tags: ["river", "great-lakes-connecting", "coldwater"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "niagara-river-upper",
    name: "Niagara River - Upper",
    type: "River",
    region: "Niagara",
    lat: 42.947,
    lon: -78.918,
    species: ["Smallmouth Bass", "Walleye", "Northern Pike", "Panfish", "Common Carp"],
    pressureLevel: "medium",
    accessibility: "medium",
    tags: ["river", "boat-access", "warmwater"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "long-point-bay",
    name: "Long Point Bay",
    type: "Bay",
    region: "Norfolk / Lake Erie",
    lat: 42.606,
    lon: -80.393,
    species: ["Largemouth Bass", "Smallmouth Bass", "Northern Pike", "Panfish", "Common Carp", "Longnose Gar"],
    pressureLevel: "high",
    accessibility: "medium",
    tags: ["lake-erie", "wetland", "boat-access"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "lake-erie-port-colborne",
    name: "Lake Erie - Port Colborne",
    type: "Great Lake",
    region: "Niagara / Lake Erie",
    lat: 42.884,
    lon: -79.251,
    species: ["Walleye", "Smallmouth Bass", "Rainbow Trout", "Common Carp", "Panfish"],
    pressureLevel: "high",
    accessibility: "high",
    tags: ["great-lake", "harbour", "shore-access"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "lake-erie-port-stanley",
    name: "Lake Erie - Port Stanley",
    type: "Great Lake",
    region: "Elgin / Lake Erie",
    lat: 42.664,
    lon: -81.215,
    species: ["Walleye", "Smallmouth Bass", "Rainbow Trout", "Common Carp", "Channel Catfish"],
    pressureLevel: "high",
    accessibility: "high",
    tags: ["great-lake", "harbour", "offshore"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "lake-st-clair",
    name: "Lake St. Clair",
    type: "Lake",
    region: "Windsor / Essex / Chatham-Kent",
    lat: 42.428,
    lon: -82.674,
    species: ["Muskellunge", "Smallmouth Bass", "Largemouth Bass", "Walleye", "Northern Pike", "Panfish", "Common Carp", "Longnose Gar"],
    pressureLevel: "high",
    accessibility: "medium",
    tags: ["muskie", "large-lake", "boat-access"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "detroit-river-windsor",
    name: "Detroit River - Windsor",
    type: "River",
    region: "Windsor",
    lat: 42.318,
    lon: -83.04,
    species: ["Walleye", "Smallmouth Bass", "Common Carp", "Channel Catfish", "Panfish", "Muskellunge"],
    pressureLevel: "high",
    accessibility: "high",
    tags: ["river", "urban", "great-lakes-connecting"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "thames-river-london",
    name: "Thames River - London",
    type: "River",
    region: "London",
    lat: 42.984,
    lon: -81.249,
    species: ["Smallmouth Bass", "Channel Catfish", "Common Carp", "Panfish", "Northern Pike"],
    pressureLevel: "high",
    accessibility: "high",
    tags: ["urban-river", "warmwater", "shore-access"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "fanshawe-lake",
    name: "Fanshawe Lake",
    type: "Reservoir",
    region: "London",
    lat: 43.04,
    lon: -81.191,
    species: ["Largemouth Bass", "Smallmouth Bass", "Northern Pike", "Panfish", "Common Carp"],
    pressureLevel: "high",
    accessibility: "high",
    tags: ["reservoir", "urban-adjacent", "shore-access"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "wildwood-reservoir",
    name: "Wildwood Reservoir",
    type: "Reservoir",
    region: "St. Marys / Perth",
    lat: 43.252,
    lon: -81.068,
    species: ["Largemouth Bass", "Smallmouth Bass", "Northern Pike", "Panfish", "Common Carp"],
    pressureLevel: "medium",
    accessibility: "medium",
    tags: ["reservoir", "campground", "boat-access"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "lake-huron-goderich",
    name: "Lake Huron - Goderich Harbour",
    type: "Great Lake Harbour",
    region: "Huron County",
    lat: 43.741,
    lon: -81.725,
    species: ["Chinook Salmon", "Coho Salmon", "Rainbow Trout", "Brown Trout", "Lake Trout", "Smallmouth Bass"],
    pressureLevel: "medium",
    accessibility: "high",
    tags: ["great-lake", "harbour", "salmon-trout"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "saugeen-river",
    name: "Saugeen River",
    type: "River",
    region: "Bruce / Grey",
    lat: 44.435,
    lon: -81.389,
    species: ["Chinook Salmon", "Rainbow Trout", "Brown Trout", "Smallmouth Bass", "Panfish"],
    pressureLevel: "high",
    accessibility: "medium",
    tags: ["lake-huron-tributary", "seasonal-run", "river"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "notawasaga-river",
    name: "Nottawasaga River",
    type: "River",
    region: "Simcoe / Georgian Bay",
    lat: 44.521,
    lon: -80.015,
    species: ["Rainbow Trout", "Chinook Salmon", "Brown Trout", "Smallmouth Bass", "Panfish"],
    pressureLevel: "high",
    accessibility: "medium",
    tags: ["georgian-bay-tributary", "seasonal-run", "river"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "georgian-bay-parry-sound",
    name: "Georgian Bay - Parry Sound",
    type: "Great Lake Bay",
    region: "Parry Sound",
    lat: 45.347,
    lon: -80.036,
    species: ["Smallmouth Bass", "Northern Pike", "Muskellunge", "Walleye", "Lake Trout", "Panfish"],
    pressureLevel: "medium",
    accessibility: "medium",
    tags: ["georgian-bay", "islands", "boat-access"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "georgian-bay-midland",
    name: "Georgian Bay - Midland",
    type: "Great Lake Bay",
    region: "Midland / Penetanguishene",
    lat: 44.75,
    lon: -79.883,
    species: ["Smallmouth Bass", "Northern Pike", "Muskellunge", "Walleye", "Panfish"],
    pressureLevel: "high",
    accessibility: "high",
    tags: ["georgian-bay", "harbour", "boat-access"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "severn-river",
    name: "Severn River",
    type: "River",
    region: "Simcoe / Muskoka",
    lat: 44.767,
    lon: -79.73,
    species: ["Muskellunge", "Smallmouth Bass", "Largemouth Bass", "Northern Pike", "Walleye", "Panfish"],
    pressureLevel: "medium",
    accessibility: "medium",
    tags: ["river", "trent-severn", "muskie"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "trent-river",
    name: "Trent River",
    type: "River",
    region: "Trent Hills / Quinte",
    lat: 44.2,
    lon: -77.594,
    species: ["Walleye", "Smallmouth Bass", "Largemouth Bass", "Northern Pike", "Panfish", "Common Carp", "Muskellunge"],
    pressureLevel: "high",
    accessibility: "high",
    tags: ["river", "trent-severn", "shore-access"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "bay-of-quinte",
    name: "Bay of Quinte",
    type: "Bay",
    region: "Belleville / Prince Edward County",
    lat: 44.167,
    lon: -77.25,
    species: ["Walleye", "Smallmouth Bass", "Largemouth Bass", "Northern Pike", "Panfish", "Common Carp", "Longnose Gar"],
    pressureLevel: "high",
    accessibility: "high",
    tags: ["lake-ontario", "walleye", "boat-access"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "st-lawrence-river-kingston",
    name: "St. Lawrence River - Kingston",
    type: "River",
    region: "Kingston / Thousand Islands",
    lat: 44.231,
    lon: -76.486,
    species: ["Muskellunge", "Smallmouth Bass", "Walleye", "Northern Pike", "Panfish", "Common Carp"],
    pressureLevel: "high",
    accessibility: "high",
    tags: ["river", "muskie", "shore-access"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "st-lawrence-river-cornwall",
    name: "St. Lawrence River - Cornwall",
    type: "River",
    region: "Cornwall",
    lat: 45.014,
    lon: -74.729,
    species: ["Muskellunge", "Smallmouth Bass", "Walleye", "Northern Pike", "Panfish", "Common Carp", "Channel Catfish"],
    pressureLevel: "medium",
    accessibility: "high",
    tags: ["river", "muskie", "large-water"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "ottawa-river-ottawa",
    name: "Ottawa River - Ottawa",
    type: "River",
    region: "Ottawa",
    lat: 45.421,
    lon: -75.697,
    species: ["Muskellunge", "Walleye", "Smallmouth Bass", "Northern Pike", "Channel Catfish", "Common Carp", "Panfish"],
    pressureLevel: "high",
    accessibility: "high",
    tags: ["urban-river", "muskie", "shore-access"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "rideau-river-ottawa",
    name: "Rideau River - Ottawa",
    type: "River",
    region: "Ottawa",
    lat: 45.388,
    lon: -75.683,
    species: ["Largemouth Bass", "Smallmouth Bass", "Northern Pike", "Walleye", "Panfish", "Common Carp"],
    pressureLevel: "high",
    accessibility: "high",
    tags: ["urban-river", "shore-access", "warmwater"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "rideau-lake",
    name: "Big Rideau Lake",
    type: "Lake",
    region: "Rideau Lakes",
    lat: 44.732,
    lon: -76.215,
    species: ["Lake Trout", "Smallmouth Bass", "Largemouth Bass", "Northern Pike", "Walleye", "Panfish"],
    pressureLevel: "medium",
    accessibility: "medium",
    tags: ["rideau-system", "coldwater", "boat-access"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "mississippi-lake",
    name: "Mississippi Lake",
    type: "Lake",
    region: "Carleton Place / Lanark",
    lat: 45.061,
    lon: -76.146,
    species: ["Walleye", "Smallmouth Bass", "Largemouth Bass", "Northern Pike", "Panfish", "Common Carp"],
    pressureLevel: "high",
    accessibility: "high",
    tags: ["lake", "shore-access", "warmwater"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "rice-lake",
    name: "Rice Lake",
    type: "Lake",
    region: "Northumberland / Peterborough",
    lat: 44.205,
    lon: -78.111,
    species: ["Walleye", "Largemouth Bass", "Smallmouth Bass", "Muskellunge", "Panfish", "Common Carp"],
    pressureLevel: "high",
    accessibility: "high",
    tags: ["kawarthas", "trent-severn", "warmwater"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "stony-lake",
    name: "Stony Lake",
    type: "Lake",
    region: "Kawarthas",
    lat: 44.556,
    lon: -78.109,
    species: ["Muskellunge", "Smallmouth Bass", "Largemouth Bass", "Walleye", "Panfish"],
    pressureLevel: "medium",
    accessibility: "medium",
    tags: ["kawarthas", "muskie", "boat-access"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "chemong-lake",
    name: "Chemong Lake",
    type: "Lake",
    region: "Kawarthas",
    lat: 44.436,
    lon: -78.386,
    species: ["Muskellunge", "Walleye", "Largemouth Bass", "Smallmouth Bass", "Panfish", "Common Carp"],
    pressureLevel: "high",
    accessibility: "high",
    tags: ["kawarthas", "muskie", "shore-access"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "pigeon-lake",
    name: "Pigeon Lake",
    type: "Lake",
    region: "Kawarthas",
    lat: 44.491,
    lon: -78.496,
    species: ["Muskellunge", "Walleye", "Largemouth Bass", "Smallmouth Bass", "Panfish", "Common Carp"],
    pressureLevel: "high",
    accessibility: "high",
    tags: ["kawarthas", "muskie", "trent-severn"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "buckhorn-lake",
    name: "Buckhorn Lake",
    type: "Lake",
    region: "Kawarthas",
    lat: 44.56,
    lon: -78.345,
    species: ["Muskellunge", "Walleye", "Largemouth Bass", "Smallmouth Bass", "Panfish"],
    pressureLevel: "medium",
    accessibility: "medium",
    tags: ["kawarthas", "muskie", "boat-access"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "sturgeon-lake-kawarthas",
    name: "Sturgeon Lake",
    type: "Lake",
    region: "Kawarthas",
    lat: 44.47,
    lon: -78.712,
    species: ["Muskellunge", "Walleye", "Largemouth Bass", "Smallmouth Bass", "Panfish", "Common Carp"],
    pressureLevel: "high",
    accessibility: "high",
    tags: ["kawarthas", "muskie", "warmwater"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "balsam-lake",
    name: "Balsam Lake",
    type: "Lake",
    region: "Kawarthas",
    lat: 44.583,
    lon: -78.856,
    species: ["Muskellunge", "Walleye", "Smallmouth Bass", "Largemouth Bass", "Panfish"],
    pressureLevel: "high",
    accessibility: "high",
    tags: ["kawarthas", "muskie", "provincial-park"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "cameron-lake",
    name: "Cameron Lake",
    type: "Lake",
    region: "Kawarthas",
    lat: 44.545,
    lon: -78.734,
    species: ["Muskellunge", "Smallmouth Bass", "Largemouth Bass", "Walleye", "Panfish"],
    pressureLevel: "high",
    accessibility: "high",
    tags: ["kawarthas", "muskie", "shore-access"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "lake-scugog",
    name: "Lake Scugog",
    type: "Lake",
    region: "Durham / Kawarthas",
    lat: 44.151,
    lon: -78.888,
    species: ["Muskellunge", "Largemouth Bass", "Panfish", "Common Carp"],
    pressureLevel: "high",
    accessibility: "high",
    tags: ["kawarthas", "muskie", "shallow-lake"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "canal-lake",
    name: "Canal Lake",
    type: "Lake",
    region: "Kawarthas / City of Kawartha Lakes",
    lat: 44.587,
    lon: -79.02,
    species: ["Largemouth Bass", "Smallmouth Bass", "Northern Pike", "Panfish", "Common Carp"],
    pressureLevel: "medium",
    accessibility: "medium",
    tags: ["kawarthas", "trent-severn", "warmwater"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "lake-couchiching",
    name: "Lake Couchiching",
    type: "Lake",
    region: "Orillia / Simcoe",
    lat: 44.666,
    lon: -79.376,
    species: ["Smallmouth Bass", "Largemouth Bass", "Northern Pike", "Walleye", "Panfish"],
    pressureLevel: "high",
    accessibility: "high",
    tags: ["large-lake", "shore-access", "warmwater"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "lake-muskoka",
    name: "Lake Muskoka",
    type: "Lake",
    region: "Muskoka",
    lat: 45.025,
    lon: -79.494,
    species: ["Smallmouth Bass", "Largemouth Bass", "Northern Pike", "Lake Trout", "Walleye", "Panfish"],
    pressureLevel: "high",
    accessibility: "medium",
    tags: ["muskoka", "cottage-country", "boat-access"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "lake-rosseau",
    name: "Lake Rosseau",
    type: "Lake",
    region: "Muskoka",
    lat: 45.16,
    lon: -79.615,
    species: ["Lake Trout", "Smallmouth Bass", "Northern Pike", "Panfish"],
    pressureLevel: "medium",
    accessibility: "medium",
    tags: ["muskoka", "coldwater", "boat-access"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "lake-joseph",
    name: "Lake Joseph",
    type: "Lake",
    region: "Muskoka",
    lat: 45.189,
    lon: -79.758,
    species: ["Lake Trout", "Smallmouth Bass", "Northern Pike", "Panfish"],
    pressureLevel: "medium",
    accessibility: "medium",
    tags: ["muskoka", "coldwater", "boat-access"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "fairy-lake-huntsville",
    name: "Fairy Lake",
    type: "Lake",
    region: "Huntsville / Muskoka",
    lat: 45.329,
    lon: -79.179,
    species: ["Lake Trout", "Smallmouth Bass", "Northern Pike", "Panfish"],
    pressureLevel: "medium",
    accessibility: "medium",
    tags: ["muskoka", "coldwater", "cottage-country"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "mary-lake",
    name: "Mary Lake",
    type: "Lake",
    region: "Huntsville / Muskoka",
    lat: 45.255,
    lon: -79.28,
    species: ["Smallmouth Bass", "Largemouth Bass", "Northern Pike", "Panfish"],
    pressureLevel: "medium",
    accessibility: "medium",
    tags: ["muskoka", "cottage-country", "warmwater"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "lake-of-bays",
    name: "Lake of Bays",
    type: "Lake",
    region: "Muskoka / Haliburton",
    lat: 45.27,
    lon: -79.015,
    species: ["Lake Trout", "Smallmouth Bass", "Northern Pike", "Panfish"],
    pressureLevel: "medium",
    accessibility: "medium",
    tags: ["muskoka", "coldwater", "boat-access"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "haliburton-lake",
    name: "Haliburton Lake",
    type: "Lake",
    region: "Haliburton Highlands",
    lat: 45.127,
    lon: -78.513,
    species: ["Lake Trout", "Smallmouth Bass", "Panfish"],
    pressureLevel: "medium",
    accessibility: "medium",
    tags: ["haliburton", "coldwater", "cottage-country"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "kennisis-lake",
    name: "Kennisis Lake",
    type: "Lake",
    region: "Haliburton Highlands",
    lat: 45.199,
    lon: -78.652,
    species: ["Lake Trout", "Smallmouth Bass", "Panfish"],
    pressureLevel: "medium",
    accessibility: "medium",
    tags: ["haliburton", "coldwater", "boat-access"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "mazinaw-lake",
    name: "Mazinaw Lake",
    type: "Lake",
    region: "Bon Echo / Lennox and Addington",
    lat: 44.895,
    lon: -77.208,
    species: ["Lake Trout", "Smallmouth Bass", "Northern Pike", "Panfish"],
    pressureLevel: "medium",
    accessibility: "medium",
    tags: ["provincial-park", "coldwater", "deep-lake"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "lake-opinicon",
    name: "Lake Opinicon",
    type: "Lake",
    region: "Rideau Lakes",
    lat: 44.56,
    lon: -76.317,
    species: ["Largemouth Bass", "Smallmouth Bass", "Northern Pike", "Panfish", "Common Carp"],
    pressureLevel: "medium",
    accessibility: "medium",
    tags: ["rideau-system", "warmwater", "boat-access"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "charleston-lake",
    name: "Charleston Lake",
    type: "Lake",
    region: "Leeds and Grenville",
    lat: 44.535,
    lon: -75.999,
    species: ["Lake Trout", "Smallmouth Bass", "Largemouth Bass", "Northern Pike", "Panfish"],
    pressureLevel: "medium",
    accessibility: "medium",
    tags: ["provincial-park", "coldwater", "boat-access"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "opeongo-lake",
    name: "Opeongo Lake",
    type: "Lake",
    region: "Algonquin Provincial Park",
    lat: 45.669,
    lon: -78.359,
    species: ["Lake Trout", "Brook Trout", "Smallmouth Bass"],
    pressureLevel: "medium",
    accessibility: "medium",
    tags: ["algonquin", "provincial-park", "coldwater"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "canoe-lake-algonquin",
    name: "Canoe Lake",
    type: "Lake",
    region: "Algonquin Provincial Park",
    lat: 45.536,
    lon: -78.707,
    species: ["Lake Trout", "Brook Trout", "Smallmouth Bass"],
    pressureLevel: "high",
    accessibility: "medium",
    tags: ["algonquin", "provincial-park", "canoe-access"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "lake-of-two-rivers",
    name: "Lake of Two Rivers",
    type: "Lake",
    region: "Algonquin Provincial Park",
    lat: 45.578,
    lon: -78.506,
    species: ["Lake Trout", "Smallmouth Bass", "Panfish"],
    pressureLevel: "high",
    accessibility: "high",
    tags: ["algonquin", "provincial-park", "highway-access"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "rock-lake-algonquin",
    name: "Rock Lake",
    type: "Lake",
    region: "Algonquin Provincial Park",
    lat: 45.526,
    lon: -78.408,
    species: ["Lake Trout", "Smallmouth Bass", "Panfish"],
    pressureLevel: "medium",
    accessibility: "medium",
    tags: ["algonquin", "provincial-park", "coldwater"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "lake-nipissing",
    name: "Lake Nipissing",
    type: "Lake",
    region: "North Bay / Nipissing",
    lat: 46.252,
    lon: -79.873,
    species: ["Walleye", "Muskellunge", "Northern Pike", "Smallmouth Bass", "Panfish"],
    pressureLevel: "high",
    accessibility: "medium",
    tags: ["northern-ontario", "muskie", "large-lake"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "french-river",
    name: "French River",
    type: "River",
    region: "Nipissing / Sudbury",
    lat: 46.096,
    lon: -80.582,
    species: ["Muskellunge", "Walleye", "Northern Pike", "Smallmouth Bass", "Panfish"],
    pressureLevel: "medium",
    accessibility: "medium",
    tags: ["river", "provincial-park", "muskie"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "moon-river",
    name: "Moon River",
    type: "River",
    region: "Muskoka / Georgian Bay",
    lat: 45.154,
    lon: -79.992,
    species: ["Muskellunge", "Walleye", "Smallmouth Bass", "Northern Pike", "Panfish"],
    pressureLevel: "medium",
    accessibility: "medium",
    tags: ["river", "georgian-bay", "muskie"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "lake-temagami",
    name: "Lake Temagami",
    type: "Lake",
    region: "Temagami",
    lat: 46.982,
    lon: -80.037,
    species: ["Lake Trout", "Walleye", "Northern Pike", "Smallmouth Bass", "Panfish"],
    pressureLevel: "medium",
    accessibility: "medium",
    tags: ["northern-ontario", "coldwater", "large-lake"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "lake-wanapitei",
    name: "Lake Wanapitei",
    type: "Lake",
    region: "Sudbury",
    lat: 46.8,
    lon: -80.75,
    species: ["Lake Trout", "Walleye", "Northern Pike", "Smallmouth Bass", "Panfish"],
    pressureLevel: "medium",
    accessibility: "medium",
    tags: ["northern-ontario", "coldwater", "large-lake"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "lake-superior-thunder-bay",
    name: "Lake Superior - Thunder Bay",
    type: "Great Lake",
    region: "Thunder Bay",
    lat: 48.407,
    lon: -89.246,
    species: ["Lake Trout", "Rainbow Trout", "Brook Trout", "Chinook Salmon", "Coho Salmon", "Northern Pike", "Smallmouth Bass"],
    pressureLevel: "medium",
    accessibility: "high",
    tags: ["great-lake", "coldwater", "harbour"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "nipigon-river",
    name: "Nipigon River",
    type: "River",
    region: "Thunder Bay District",
    lat: 49.017,
    lon: -88.259,
    species: ["Brook Trout", "Lake Trout", "Rainbow Trout", "Chinook Salmon", "Coho Salmon", "Walleye", "Northern Pike"],
    pressureLevel: "medium",
    accessibility: "medium",
    tags: ["river", "coldwater", "northern-ontario"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "lake-nipigon",
    name: "Lake Nipigon",
    type: "Lake",
    region: "Thunder Bay District",
    lat: 49.832,
    lon: -88.569,
    species: ["Lake Trout", "Brook Trout", "Walleye", "Northern Pike", "Panfish"],
    pressureLevel: "low",
    accessibility: "low",
    tags: ["northern-ontario", "large-lake", "coldwater"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "lac-seul",
    name: "Lac Seul",
    type: "Lake",
    region: "Northwestern Ontario",
    lat: 50.255,
    lon: -92.291,
    species: ["Walleye", "Northern Pike", "Muskellunge", "Smallmouth Bass", "Panfish"],
    pressureLevel: "medium",
    accessibility: "low",
    tags: ["northwestern-ontario", "muskie", "walleye"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "lake-of-the-woods",
    name: "Lake of the Woods",
    type: "Lake",
    region: "Kenora",
    lat: 49.183,
    lon: -94.0,
    species: ["Walleye", "Muskellunge", "Northern Pike", "Smallmouth Bass", "Lake Trout", "Panfish"],
    pressureLevel: "medium",
    accessibility: "medium",
    tags: ["northwestern-ontario", "muskie", "large-lake"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "eagle-lake",
    name: "Eagle Lake",
    type: "Lake",
    region: "Dryden / Northwestern Ontario",
    lat: 49.73,
    lon: -93.13,
    species: ["Muskellunge", "Walleye", "Northern Pike", "Smallmouth Bass", "Lake Trout", "Panfish"],
    pressureLevel: "medium",
    accessibility: "low",
    tags: ["northwestern-ontario", "muskie", "boat-access"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "speed-river-guelph",
    name: "Speed River - Guelph",
    type: "River",
    region: "Guelph / Wellington",
    lat: 43.545,
    lon: -80.25,
    species: ["Smallmouth Bass", "Panfish", "Common Carp", "Northern Pike"],
    pressureLevel: "high",
    accessibility: "veryHigh",
    tags: ["urban-river", "shore-access", "warmwater"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "eramosa-river-guelph",
    name: "Eramosa River - Guelph",
    type: "River",
    region: "Guelph / Wellington",
    lat: 43.543,
    lon: -80.235,
    species: ["Smallmouth Bass", "Panfish", "Common Carp"],
    pressureLevel: "high",
    accessibility: "high",
    tags: ["urban-river", "shore-access", "warmwater"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "laurel-creek-reservoir",
    name: "Laurel Creek Reservoir",
    type: "Reservoir",
    region: "Waterloo",
    lat: 43.474,
    lon: -80.564,
    species: ["Largemouth Bass", "Panfish", "Common Carp"],
    pressureLevel: "high",
    accessibility: "high",
    tags: ["reservoir", "conservation-area", "urban-adjacent"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "columbia-lake-waterloo",
    name: "Columbia Lake",
    type: "Urban Lake",
    region: "Waterloo",
    lat: 43.475,
    lon: -80.548,
    species: ["Common Carp", "Panfish", "Largemouth Bass"],
    pressureLevel: "high",
    accessibility: "veryHigh",
    tags: ["urban", "shore-access", "campus"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "grand-river-kitchener-waterloo",
    name: "Grand River - Kitchener / Waterloo",
    type: "River",
    region: "Kitchener / Waterloo",
    lat: 43.463,
    lon: -80.469,
    species: ["Smallmouth Bass", "Panfish", "Common Carp", "Channel Catfish"],
    pressureLevel: "high",
    accessibility: "high",
    tags: ["urban-river", "shore-access", "warmwater"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "grand-river-cambridge",
    name: "Grand River - Cambridge",
    type: "River",
    region: "Cambridge",
    lat: 43.361,
    lon: -80.314,
    species: ["Smallmouth Bass", "Walleye", "Panfish", "Common Carp", "Channel Catfish"],
    pressureLevel: "high",
    accessibility: "high",
    tags: ["urban-river", "shore-access", "warmwater"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "shades-mills-reservoir",
    name: "Shade's Mills Reservoir",
    type: "Reservoir",
    region: "Cambridge",
    lat: 43.397,
    lon: -80.292,
    species: ["Largemouth Bass", "Panfish", "Common Carp", "Rainbow Trout"],
    pressureLevel: "high",
    accessibility: "high",
    tags: ["reservoir", "conservation-area", "urban-adjacent"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "island-lake-orangeville",
    name: "Island Lake",
    type: "Reservoir",
    region: "Orangeville / Headwaters",
    lat: 43.927,
    lon: -80.077,
    species: ["Northern Pike", "Largemouth Bass", "Smallmouth Bass", "Panfish"],
    pressureLevel: "high",
    accessibility: "high",
    tags: ["reservoir", "conservation-area", "shore-access"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "professors-lake",
    name: "Professor's Lake",
    type: "Urban Lake",
    region: "Brampton",
    lat: 43.735,
    lon: -79.739,
    species: ["Panfish", "Common Carp", "Largemouth Bass"],
    pressureLevel: "veryHigh",
    accessibility: "veryHigh",
    tags: ["urban", "shore-access", "beginner-friendly"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "heart-lake-brampton",
    name: "Heart Lake",
    type: "Kettle Lake",
    region: "Brampton",
    lat: 43.741,
    lon: -79.797,
    species: ["Panfish", "Largemouth Bass", "Rainbow Trout"],
    pressureLevel: "high",
    accessibility: "high",
    tags: ["conservation-area", "shore-access", "urban-adjacent"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "credit-river-streetsville",
    name: "Credit River - Streetsville",
    type: "River",
    region: "Mississauga",
    lat: 43.578,
    lon: -79.713,
    species: ["Chinook Salmon", "Rainbow Trout", "Brown Trout", "Smallmouth Bass", "Common Carp"],
    pressureLevel: "veryHigh",
    accessibility: "high",
    tags: ["urban-river", "lake-ontario-tributary", "seasonal-run"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "etobicoke-creek-lower",
    name: "Etobicoke Creek - Lower",
    type: "Creek",
    region: "Toronto / Mississauga",
    lat: 43.592,
    lon: -79.543,
    species: ["Common Carp", "Panfish", "Chinook Salmon", "Rainbow Trout", "Brown Trout"],
    pressureLevel: "veryHigh",
    accessibility: "high",
    tags: ["urban-creek", "lake-ontario-tributary", "seasonal-run"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "mimico-creek-lower",
    name: "Mimico Creek - Lower",
    type: "Creek",
    region: "Toronto",
    lat: 43.621,
    lon: -79.481,
    species: ["Common Carp", "Panfish", "Chinook Salmon", "Rainbow Trout"],
    pressureLevel: "veryHigh",
    accessibility: "high",
    tags: ["urban-creek", "lake-ontario-tributary", "seasonal-run"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "ashbridges-bay",
    name: "Ashbridges Bay",
    type: "Bay",
    region: "Toronto",
    lat: 43.659,
    lon: -79.312,
    species: ["Common Carp", "Panfish", "Northern Pike", "Largemouth Bass", "Smallmouth Bass"],
    pressureLevel: "veryHigh",
    accessibility: "veryHigh",
    tags: ["urban-bay", "shore-access", "lake-ontario"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "tommy-thompson-park",
    name: "Tommy Thompson Park",
    type: "Urban Shoreline",
    region: "Toronto",
    lat: 43.626,
    lon: -79.331,
    species: ["Common Carp", "Northern Pike", "Smallmouth Bass", "Panfish"],
    pressureLevel: "high",
    accessibility: "high",
    tags: ["urban-shore", "lake-ontario", "bike-access"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "bluffers-park",
    name: "Bluffer's Park",
    type: "Harbour",
    region: "Toronto",
    lat: 43.706,
    lon: -79.23,
    species: ["Common Carp", "Smallmouth Bass", "Panfish", "Chinook Salmon", "Rainbow Trout"],
    pressureLevel: "veryHigh",
    accessibility: "veryHigh",
    tags: ["urban-harbour", "shore-access", "lake-ontario"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "oakville-harbour",
    name: "Oakville Harbour",
    type: "Harbour",
    region: "Oakville",
    lat: 43.441,
    lon: -79.666,
    species: ["Common Carp", "Smallmouth Bass", "Panfish", "Chinook Salmon", "Rainbow Trout", "Brown Trout"],
    pressureLevel: "high",
    accessibility: "veryHigh",
    tags: ["harbour", "shore-access", "lake-ontario"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "lasalle-park-marina",
    name: "LaSalle Park Marina",
    type: "Harbour Shoreline",
    region: "Burlington",
    lat: 43.3,
    lon: -79.843,
    species: ["Common Carp", "Channel Catfish", "Panfish", "Largemouth Bass", "Northern Pike"],
    pressureLevel: "veryHigh",
    accessibility: "veryHigh",
    tags: ["urban-harbour", "shore-access", "hamilton-harbour"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "kelso-reservoir",
    name: "Kelso Reservoir",
    type: "Reservoir",
    region: "Milton / Halton",
    lat: 43.51,
    lon: -79.94,
    species: ["Largemouth Bass", "Panfish", "Rainbow Trout"],
    pressureLevel: "high",
    accessibility: "high",
    tags: ["reservoir", "conservation-area", "shore-access"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "mountsberg-reservoir",
    name: "Mountsberg Reservoir",
    type: "Reservoir",
    region: "Hamilton / Halton",
    lat: 43.471,
    lon: -80.025,
    species: ["Northern Pike", "Largemouth Bass", "Panfish", "Common Carp"],
    pressureLevel: "medium",
    accessibility: "high",
    tags: ["reservoir", "conservation-area", "shore-access"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "valens-lake",
    name: "Valens Lake",
    type: "Reservoir",
    region: "Hamilton",
    lat: 43.375,
    lon: -80.139,
    species: ["Largemouth Bass", "Northern Pike", "Panfish", "Common Carp"],
    pressureLevel: "medium",
    accessibility: "high",
    tags: ["reservoir", "conservation-area", "campground"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "christie-lake",
    name: "Christie Lake",
    type: "Reservoir",
    region: "Hamilton / Dundas",
    lat: 43.28,
    lon: -80.027,
    species: ["Largemouth Bass", "Smallmouth Bass", "Northern Pike", "Panfish", "Common Carp"],
    pressureLevel: "high",
    accessibility: "high",
    tags: ["reservoir", "conservation-area", "shore-access"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "fifty-point-conservation-area",
    name: "Fifty Point Conservation Area",
    type: "Lake Ontario Shoreline",
    region: "Hamilton / Niagara",
    lat: 43.216,
    lon: -79.627,
    species: ["Common Carp", "Smallmouth Bass", "Panfish", "Chinook Salmon", "Rainbow Trout", "Brown Trout"],
    pressureLevel: "high",
    accessibility: "high",
    tags: ["lake-ontario", "shore-access", "conservation-area"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "springbank-park-thames-river",
    name: "Thames River - Springbank Park",
    type: "River",
    region: "London",
    lat: 42.963,
    lon: -81.312,
    species: ["Smallmouth Bass", "Channel Catfish", "Common Carp", "Panfish", "Northern Pike"],
    pressureLevel: "high",
    accessibility: "veryHigh",
    tags: ["urban-river", "shore-access", "park"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "pittock-reservoir",
    name: "Pittock Reservoir",
    type: "Reservoir",
    region: "Woodstock / Oxford",
    lat: 43.145,
    lon: -80.735,
    species: ["Largemouth Bass", "Smallmouth Bass", "Northern Pike", "Panfish", "Common Carp"],
    pressureLevel: "medium",
    accessibility: "high",
    tags: ["reservoir", "conservation-area", "shore-access"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "barrie-waterfront-lake-simcoe",
    name: "Barrie Waterfront - Lake Simcoe",
    type: "Lake Shoreline",
    region: "Barrie",
    lat: 44.39,
    lon: -79.69,
    species: ["Smallmouth Bass", "Northern Pike", "Panfish", "Lake Trout"],
    pressureLevel: "veryHigh",
    accessibility: "veryHigh",
    tags: ["urban-shore", "large-lake", "shore-access"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "little-lake-barrie",
    name: "Little Lake",
    type: "Lake",
    region: "Barrie",
    lat: 44.417,
    lon: -79.684,
    species: ["Largemouth Bass", "Northern Pike", "Panfish", "Common Carp"],
    pressureLevel: "high",
    accessibility: "high",
    tags: ["urban-lake", "shore-access", "warmwater"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "dows-lake",
    name: "Dow's Lake",
    type: "Urban Lake",
    region: "Ottawa",
    lat: 45.398,
    lon: -75.705,
    species: ["Common Carp", "Panfish", "Largemouth Bass", "Northern Pike"],
    pressureLevel: "veryHigh",
    accessibility: "veryHigh",
    tags: ["urban", "rideau-canal", "shore-access"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "petrie-island",
    name: "Petrie Island",
    type: "River Backwater",
    region: "Ottawa",
    lat: 45.501,
    lon: -75.491,
    species: ["Largemouth Bass", "Smallmouth Bass", "Northern Pike", "Walleye", "Panfish", "Common Carp"],
    pressureLevel: "high",
    accessibility: "high",
    tags: ["ottawa-river", "shore-access", "urban-edge"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "mooneys-bay",
    name: "Mooney's Bay",
    type: "River Bay",
    region: "Ottawa",
    lat: 45.37,
    lon: -75.693,
    species: ["Common Carp", "Panfish", "Largemouth Bass", "Northern Pike"],
    pressureLevel: "veryHigh",
    accessibility: "veryHigh",
    tags: ["urban", "rideau-river", "shore-access"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "cataraqui-river-kingston",
    name: "Cataraqui River - Kingston",
    type: "River",
    region: "Kingston",
    lat: 44.236,
    lon: -76.48,
    species: ["Largemouth Bass", "Smallmouth Bass", "Northern Pike", "Panfish", "Common Carp"],
    pressureLevel: "high",
    accessibility: "high",
    tags: ["urban-river", "rideau-system", "shore-access"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "collins-bay",
    name: "Collins Bay",
    type: "Bay",
    region: "Kingston",
    lat: 44.233,
    lon: -76.61,
    species: ["Largemouth Bass", "Smallmouth Bass", "Northern Pike", "Panfish", "Common Carp"],
    pressureLevel: "high",
    accessibility: "high",
    tags: ["lake-ontario", "urban-bay", "shore-access"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "otonabee-river-peterborough",
    name: "Otonabee River - Peterborough",
    type: "River",
    region: "Peterborough",
    lat: 44.304,
    lon: -78.319,
    species: ["Muskellunge", "Walleye", "Smallmouth Bass", "Largemouth Bass", "Panfish", "Common Carp"],
    pressureLevel: "high",
    accessibility: "high",
    tags: ["urban-river", "trent-severn", "muskie"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "little-lake-peterborough",
    name: "Little Lake",
    type: "Urban Lake",
    region: "Peterborough",
    lat: 44.298,
    lon: -78.318,
    species: ["Muskellunge", "Walleye", "Largemouth Bass", "Smallmouth Bass", "Panfish", "Common Carp"],
    pressureLevel: "veryHigh",
    accessibility: "veryHigh",
    tags: ["urban", "trent-severn", "shore-access"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "jordan-harbour",
    name: "Jordan Harbour",
    type: "Harbour",
    region: "Niagara",
    lat: 43.2,
    lon: -79.368,
    species: ["Common Carp", "Panfish", "Largemouth Bass", "Northern Pike", "Chinook Salmon", "Rainbow Trout"],
    pressureLevel: "high",
    accessibility: "high",
    tags: ["lake-ontario", "harbour", "shore-access"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "welland-river",
    name: "Welland River",
    type: "River",
    region: "Niagara",
    lat: 43.063,
    lon: -79.121,
    species: ["Smallmouth Bass", "Largemouth Bass", "Northern Pike", "Panfish", "Common Carp", "Channel Catfish"],
    pressureLevel: "medium",
    accessibility: "medium",
    tags: ["river", "warmwater", "shore-access"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "welland-canal-recreational-waterway",
    name: "Welland Canal Recreational Waterway",
    type: "Canal",
    region: "Welland / Niagara",
    lat: 42.993,
    lon: -79.249,
    species: ["Smallmouth Bass", "Largemouth Bass", "Panfish", "Common Carp"],
    pressureLevel: "high",
    accessibility: "high",
    tags: ["urban", "canal", "shore-access"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "lake-erie-port-dover",
    name: "Lake Erie - Port Dover",
    type: "Great Lake Harbour",
    region: "Norfolk / Lake Erie",
    lat: 42.785,
    lon: -80.204,
    species: ["Walleye", "Smallmouth Bass", "Common Carp", "Channel Catfish", "Rainbow Trout"],
    pressureLevel: "high",
    accessibility: "high",
    tags: ["lake-erie", "harbour", "shore-access"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "peche-island",
    name: "Peche Island",
    type: "River Island",
    region: "Windsor",
    lat: 42.339,
    lon: -82.928,
    species: ["Smallmouth Bass", "Walleye", "Northern Pike", "Muskellunge", "Common Carp", "Panfish"],
    pressureLevel: "medium",
    accessibility: "medium",
    tags: ["detroit-river", "boat-access", "urban-adjacent"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "canard-river",
    name: "Canard River",
    type: "River",
    region: "Windsor / Essex",
    lat: 42.176,
    lon: -83.064,
    species: ["Largemouth Bass", "Northern Pike", "Panfish", "Common Carp", "Channel Catfish"],
    pressureLevel: "medium",
    accessibility: "medium",
    tags: ["river", "warmwater", "urban-adjacent"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "rondeau-bay",
    name: "Rondeau Bay",
    type: "Bay",
    region: "Chatham-Kent / Lake Erie",
    lat: 42.289,
    lon: -81.866,
    species: ["Largemouth Bass", "Northern Pike", "Panfish", "Common Carp", "Channel Catfish"],
    pressureLevel: "medium",
    accessibility: "medium",
    tags: ["lake-erie", "bay", "warmwater"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "st-clair-river-sarnia",
    name: "St. Clair River - Sarnia",
    type: "River",
    region: "Sarnia / Lambton",
    lat: 42.974,
    lon: -82.406,
    species: ["Walleye", "Smallmouth Bass", "Muskellunge", "Northern Pike", "Common Carp", "Channel Catfish"],
    pressureLevel: "high",
    accessibility: "high",
    tags: ["river", "great-lakes-connecting", "shore-access"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "sydenham-river-wallaceburg",
    name: "Sydenham River - Wallaceburg",
    type: "River",
    region: "Chatham-Kent",
    lat: 42.594,
    lon: -82.389,
    species: ["Smallmouth Bass", "Northern Pike", "Panfish", "Common Carp", "Channel Catfish"],
    pressureLevel: "medium",
    accessibility: "high",
    tags: ["river", "urban", "warmwater"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "maitland-river-goderich",
    name: "Maitland River - Goderich",
    type: "River",
    region: "Huron County",
    lat: 43.735,
    lon: -81.709,
    species: ["Rainbow Trout", "Brown Trout", "Chinook Salmon", "Smallmouth Bass"],
    pressureLevel: "high",
    accessibility: "medium",
    tags: ["lake-huron-tributary", "seasonal-run", "river"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "lake-erie-wheatley",
    name: "Lake Erie - Wheatley Harbour",
    type: "Great Lake Harbour",
    region: "Chatham-Kent / Lake Erie",
    lat: 42.092,
    lon: -82.461,
    species: ["Walleye", "Smallmouth Bass", "Rainbow Trout", "Common Carp", "Channel Catfish"],
    pressureLevel: "medium",
    accessibility: "high",
    tags: ["lake-erie", "harbour", "shore-access"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "duffins-creek-lower",
    name: "Duffins Creek - Lower",
    type: "Creek",
    region: "Ajax / Pickering",
    lat: 43.819,
    lon: -79.07,
    species: ["Chinook Salmon", "Rainbow Trout", "Brown Trout", "Common Carp", "Panfish"],
    pressureLevel: "high",
    accessibility: "high",
    tags: ["lake-ontario-tributary", "seasonal-run", "urban-edge"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "oshawa-harbour",
    name: "Oshawa Harbour",
    type: "Harbour",
    region: "Oshawa / Durham",
    lat: 43.865,
    lon: -78.835,
    species: ["Common Carp", "Panfish", "Smallmouth Bass", "Northern Pike", "Chinook Salmon", "Rainbow Trout"],
    pressureLevel: "high",
    accessibility: "high",
    tags: ["lake-ontario", "harbour", "shore-access"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "whitby-harbour",
    name: "Whitby Harbour",
    type: "Harbour",
    region: "Whitby / Durham",
    lat: 43.85,
    lon: -78.94,
    species: ["Common Carp", "Panfish", "Smallmouth Bass", "Chinook Salmon", "Rainbow Trout", "Brown Trout"],
    pressureLevel: "high",
    accessibility: "veryHigh",
    tags: ["lake-ontario", "harbour", "shore-access"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "highland-creek-lower",
    name: "Highland Creek - Lower",
    type: "Creek",
    region: "Scarborough",
    lat: 43.775,
    lon: -79.146,
    species: ["Chinook Salmon", "Rainbow Trout", "Brown Trout", "Common Carp", "Panfish"],
    pressureLevel: "high",
    accessibility: "high",
    tags: ["urban-creek", "lake-ontario-tributary", "seasonal-run"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "lake-wilcox",
    name: "Lake Wilcox",
    type: "Urban Lake",
    region: "Richmond Hill / York",
    lat: 43.949,
    lon: -79.435,
    species: ["Largemouth Bass", "Panfish", "Common Carp"],
    pressureLevel: "veryHigh",
    accessibility: "veryHigh",
    tags: ["urban-lake", "shore-access", "beginner-friendly"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "ganaraska-river-port-hope",
    name: "Ganaraska River - Port Hope",
    type: "River",
    region: "Port Hope / Northumberland",
    lat: 43.951,
    lon: -78.293,
    species: ["Chinook Salmon", "Coho Salmon", "Rainbow Trout", "Brown Trout"],
    pressureLevel: "veryHigh",
    accessibility: "high",
    tags: ["lake-ontario-tributary", "seasonal-run", "shore-access"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "moira-river-belleville",
    name: "Moira River - Belleville",
    type: "River",
    region: "Belleville / Bay of Quinte",
    lat: 44.165,
    lon: -77.383,
    species: ["Walleye", "Smallmouth Bass", "Northern Pike", "Panfish", "Common Carp"],
    pressureLevel: "high",
    accessibility: "high",
    tags: ["urban-river", "bay-of-quinte", "shore-access"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "madawaska-river-arnprior",
    name: "Madawaska River - Arnprior",
    type: "River",
    region: "Arnprior / Renfrew County",
    lat: 45.435,
    lon: -76.357,
    species: ["Walleye", "Smallmouth Bass", "Northern Pike", "Panfish"],
    pressureLevel: "medium",
    accessibility: "medium",
    tags: ["river", "ottawa-valley", "shore-access"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "calabogie-lake",
    name: "Calabogie Lake",
    type: "Lake",
    region: "Renfrew County",
    lat: 45.272,
    lon: -76.737,
    species: ["Walleye", "Smallmouth Bass", "Northern Pike", "Panfish"],
    pressureLevel: "medium",
    accessibility: "medium",
    tags: ["ottawa-valley", "cottage-country", "boat-access"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "muskrat-lake",
    name: "Muskrat Lake",
    type: "Lake",
    region: "Cobden / Ottawa Valley",
    lat: 45.624,
    lon: -76.883,
    species: ["Walleye", "Smallmouth Bass", "Northern Pike", "Panfish", "Common Carp"],
    pressureLevel: "medium",
    accessibility: "medium",
    tags: ["ottawa-valley", "boat-access", "warmwater"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "clear-lake-kawarthas",
    name: "Clear Lake",
    type: "Lake",
    region: "Kawarthas",
    lat: 44.526,
    lon: -78.228,
    species: ["Muskellunge", "Walleye", "Smallmouth Bass", "Largemouth Bass", "Panfish"],
    pressureLevel: "medium",
    accessibility: "medium",
    tags: ["kawarthas", "trent-severn", "boat-access"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "katchewanooka-lake",
    name: "Katchewanooka Lake",
    type: "Lake",
    region: "Lakefield / Peterborough County",
    lat: 44.44,
    lon: -78.269,
    species: ["Muskellunge", "Walleye", "Smallmouth Bass", "Largemouth Bass", "Panfish"],
    pressureLevel: "medium",
    accessibility: "medium",
    tags: ["kawarthas", "trent-severn", "boat-access"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "chandos-lake",
    name: "Chandos Lake",
    type: "Lake",
    region: "North Kawartha",
    lat: 44.837,
    lon: -77.987,
    species: ["Lake Trout", "Smallmouth Bass", "Largemouth Bass", "Panfish"],
    pressureLevel: "medium",
    accessibility: "medium",
    tags: ["cottage-country", "coldwater", "boat-access"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "jack-lake",
    name: "Jack Lake",
    type: "Lake",
    region: "Apsley / North Kawartha",
    lat: 44.766,
    lon: -78.011,
    species: ["Muskellunge", "Walleye", "Smallmouth Bass", "Largemouth Bass", "Panfish"],
    pressureLevel: "medium",
    accessibility: "medium",
    tags: ["kawarthas", "cottage-country", "boat-access"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "sparrow-lake",
    name: "Sparrow Lake",
    type: "Lake",
    region: "Muskoka / Severn",
    lat: 44.795,
    lon: -79.42,
    species: ["Muskellunge", "Walleye", "Northern Pike", "Smallmouth Bass", "Largemouth Bass", "Panfish"],
    pressureLevel: "medium",
    accessibility: "medium",
    tags: ["muskoka", "trent-severn", "boat-access"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "gull-lake-gravenhurst",
    name: "Gull Lake",
    type: "Lake",
    region: "Gravenhurst / Muskoka",
    lat: 44.925,
    lon: -79.382,
    species: ["Lake Trout", "Smallmouth Bass", "Northern Pike", "Panfish"],
    pressureLevel: "medium",
    accessibility: "high",
    tags: ["muskoka", "coldwater", "urban-adjacent"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "six-mile-lake",
    name: "Six Mile Lake",
    type: "Lake",
    region: "Georgian Bay Township",
    lat: 44.872,
    lon: -79.733,
    species: ["Largemouth Bass", "Smallmouth Bass", "Northern Pike", "Panfish"],
    pressureLevel: "medium",
    accessibility: "medium",
    tags: ["provincial-park", "georgian-bay", "warmwater"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "honey-harbour-georgian-bay",
    name: "Georgian Bay - Honey Harbour",
    type: "Great Lake Bay",
    region: "Georgian Bay Township",
    lat: 44.869,
    lon: -79.817,
    species: ["Smallmouth Bass", "Northern Pike", "Muskellunge", "Walleye", "Panfish"],
    pressureLevel: "high",
    accessibility: "medium",
    tags: ["georgian-bay", "muskie", "boat-access"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "lake-vernon",
    name: "Lake Vernon",
    type: "Lake",
    region: "Huntsville / Muskoka",
    lat: 45.36,
    lon: -79.29,
    species: ["Smallmouth Bass", "Largemouth Bass", "Northern Pike", "Panfish"],
    pressureLevel: "medium",
    accessibility: "medium",
    tags: ["muskoka", "cottage-country", "boat-access"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "smoke-lake-algonquin",
    name: "Smoke Lake",
    type: "Lake",
    region: "Algonquin Provincial Park",
    lat: 45.528,
    lon: -78.749,
    species: ["Lake Trout", "Brook Trout", "Smallmouth Bass"],
    pressureLevel: "high",
    accessibility: "medium",
    tags: ["algonquin", "provincial-park", "coldwater"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "cache-lake-algonquin",
    name: "Cache Lake",
    type: "Lake",
    region: "Algonquin Provincial Park",
    lat: 45.531,
    lon: -78.633,
    species: ["Lake Trout", "Smallmouth Bass", "Panfish"],
    pressureLevel: "medium",
    accessibility: "medium",
    tags: ["algonquin", "provincial-park", "coldwater"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "kawagama-lake",
    name: "Kawagama Lake",
    type: "Lake",
    region: "Haliburton / Dorset",
    lat: 45.266,
    lon: -78.789,
    species: ["Lake Trout", "Smallmouth Bass", "Northern Pike", "Panfish"],
    pressureLevel: "medium",
    accessibility: "medium",
    tags: ["haliburton", "coldwater", "boat-access"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "mattawa-river",
    name: "Mattawa River",
    type: "River",
    region: "North Bay / Mattawa",
    lat: 46.319,
    lon: -79.548,
    species: ["Walleye", "Smallmouth Bass", "Northern Pike", "Panfish"],
    pressureLevel: "medium",
    accessibility: "medium",
    tags: ["river", "northeastern-ontario", "provincial-park"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "lake-nosbonsing",
    name: "Lake Nosbonsing",
    type: "Lake",
    region: "North Bay / Bonfield",
    lat: 46.184,
    lon: -79.247,
    species: ["Walleye", "Smallmouth Bass", "Largemouth Bass", "Northern Pike", "Panfish"],
    pressureLevel: "medium",
    accessibility: "medium",
    tags: ["northeastern-ontario", "boat-access", "warmwater"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "ramsey-lake",
    name: "Ramsey Lake",
    type: "Urban Lake",
    region: "Sudbury",
    lat: 46.471,
    lon: -80.967,
    species: ["Lake Trout", "Walleye", "Smallmouth Bass", "Northern Pike", "Panfish"],
    pressureLevel: "high",
    accessibility: "high",
    tags: ["urban-lake", "northeastern-ontario", "coldwater"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "lake-timiskaming",
    name: "Lake Timiskaming",
    type: "Lake",
    region: "Temiskaming Shores",
    lat: 47.489,
    lon: -79.67,
    species: ["Walleye", "Northern Pike", "Smallmouth Bass", "Lake Trout", "Panfish"],
    pressureLevel: "medium",
    accessibility: "medium",
    tags: ["northeastern-ontario", "large-lake", "boat-access"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "rainy-lake",
    name: "Rainy Lake",
    type: "Lake",
    region: "Fort Frances / Northwestern Ontario",
    lat: 48.624,
    lon: -93.18,
    species: ["Walleye", "Northern Pike", "Smallmouth Bass", "Lake Trout", "Panfish"],
    pressureLevel: "medium",
    accessibility: "medium",
    tags: ["northwestern-ontario", "large-lake", "boat-access"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "dog-lake-thunder-bay",
    name: "Dog Lake",
    type: "Lake",
    region: "Thunder Bay District",
    lat: 48.699,
    lon: -89.69,
    species: ["Walleye", "Northern Pike", "Smallmouth Bass", "Lake Trout", "Panfish"],
    pressureLevel: "medium",
    accessibility: "medium",
    tags: ["northwestern-ontario", "large-lake", "boat-access"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "black-sturgeon-lake",
    name: "Black Sturgeon Lake",
    type: "Lake",
    region: "Kenora",
    lat: 49.901,
    lon: -94.423,
    species: ["Walleye", "Northern Pike", "Smallmouth Bass", "Lake Trout", "Panfish"],
    pressureLevel: "medium",
    accessibility: "medium",
    tags: ["northwestern-ontario", "boat-access", "coldwater"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
  {
    id: "shoal-lake-kenora",
    name: "Shoal Lake",
    type: "Lake",
    region: "Kenora / Northwestern Ontario",
    lat: 49.621,
    lon: -95.049,
    species: ["Lake Trout", "Walleye", "Northern Pike", "Smallmouth Bass", "Panfish"],
    pressureLevel: "medium",
    accessibility: "medium",
    tags: ["northwestern-ontario", "large-lake", "coldwater"],
    sourceNote: "Curated prototype entry; verify with Ontario Fish ON-Line for production.",
  },
];
